mlabs-haskell/bot-plutus-interface

mlabs-pab.cabal, src/MLabsPAB/CardanoCLI.hs, src/MLabsPAB/ChainIndex.hs, src/MLabsPAB/Contract.hs, src/MLabsPAB/Effects.hs, src/MLabsPAB/Files.hs, src/MLabsPAB/PreBalance.hs, src/MLabsPAB/Types.hs, src/MLabsPAB/UtxoParser.hs, test/Spec.hs, test/Spec/MLabsPAB/Contract.hs, test/Spec/MLabsPAB/UtxoParser.hs, test/Spec/Mock.hs, test/Spec/MockContract.hs
This PR includes a framework for testing the PAB. I changed most IO actions to freer effects, so we can run them as a pure function in the tests, and inspect the cardano-cli calls, and file read/write actions.
I will still need to write more tests and maybe refactor the framework to reduce boilerplate.
Solves: https://github.com/mlabs-haskell/mlabs-pab/issues/3
=> Test framework for the PAB effects

mlabs-pab.cabal, src/MLabsPAB/CardanoCLI.hs, src/MLabsPAB/Contract.hs, src/MLabsPAB/PreBalance.hs, src/MLabsPAB/Server.hs, src/MLabsPAB/Types.hs, src/MLabsPAB/UtxoParser.hs, test/Spec.hs, test/Spec/MLabsPAB/Contract.hs, test/Spec/MLabsPAB/PreBalance.hs, test/Spec/MockContract.hs
Solves: #10
I tried to reuse functions from the cardano-node repository, but had a few problems getting the required values for the computation (namely EraHistory and SystemStart), so I decided to use the CLI for this.
I had to add the following steps to the tx submit flow:
1. calculating minimum utxo
2. build a tx with build-raw, this doesnt include any fees yet, its only purpose is to be used in the following step
3. calculate minimum fees, this uses a tx file as its input
For the second step, I had to use the raw transaction build mode, so the cli wouldn't worry about balancing, and would create a tx even if there aren't enough inputs. However, I had to introduce execution unit calculation, which is needed by the cli in raw mode.
=> Fee calculation using the cli

mlabs-pab.cabal, src/MLabsPAB/CardanoCLI.hs, src/MLabsPAB/Contract.hs, src/MLabsPAB/Files.hs, src/MLabsPAB/Types.hs, test/Spec/MLabsPAB/Contract.hs, test/Spec/MockContract.hs
Solves: #11
Adding tx files unique names, so they don't clash when multiple txs are built at the same time.
=> Save tx files with unique file names

.github/workflows/integrate.yaml, src/MLabsPAB/PreBalance.hs, test/Spec/MLabsPAB/Contract.hs, test/Spec/MockContract.hs
`cardano-cli` will throw an error if input containing `Value` with non-Ada assets will be supplied as collateral. This PR fixes the issue by filtering out utxos which will be invalid for collateral.
=> Pick only non-Ada inputs for colalteral

mlabs-pab.cabal, src/MLabsPAB/CardanoCLI.hs, src/MLabsPAB/Contract.hs, src/MLabsPAB/Effects.hs, src/MLabsPAB/Files.hs, src/MLabsPAB/PreBalance.hs, src/MLabsPAB/Server.hs, src/MLabsPAB/Types.hs, test/Spec/MLabsPAB/Contract.hs, test/Spec/MockContract.hs
Add a simple interpreter for Writer effects.
Writer effects in the fake PAB will immediately be sent via websocket to the client in a NewObservableState message, and will not be stored in the PAB.
Another difference is that `w` in `Writer w` must have ToJSON instace, while the Monoid instance is not needed.
=> Add Writer implementation

Makefile, README.md, bot-plutus-interface.cabal, examples/plutus-game/app/Main.hs, examples/plutus-game/plutus-game.cabal, examples/plutus-nft/app/Main.hs, examples/plutus-nft/plutus-nft.cabal, flake.nix, hie.yaml, src/BotPlutusInterface.hs, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/ChainIndex.hs, src/BotPlutusInterface/Contract.hs, src/BotPlutusInterface/Effects.hs, src/BotPlutusInterface/Files.hs, src/BotPlutusInterface/PreBalance.hs, src/BotPlutusInterface/Server.hs, src/BotPlutusInterface/Types.hs, src/BotPlutusInterface/UtxoParser.hs, test/Spec.hs, test/Spec/BotPlutusInterface/Contract.hs, test/Spec/BotPlutusInterface/PreBalance.hs, test/Spec/BotPlutusInterface/UtxoParser.hs, test/Spec/MockContract.hs
Solves: #34
Note: I already renamed the repository name in github, but this should not break dependencies for current library users, all requests to the old name are redirected to the new one.
=> Rename the project to bot-plutus-interface

bot-plutus-interface.cabal, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/UtxoParser.hs, test/Spec/BotPlutusInterface/Contract.hs, test/Spec/BotPlutusInterface/UtxoParser.hs, test/Spec/MockContract.hs
=> Update asset name handling (for cardano-cli 1.32)

src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/Contract.hs, src/BotPlutusInterface/Files.hs, src/BotPlutusInterface/PreBalance.hs, test/Spec/BotPlutusInterface/Contract.hs, test/Spec/BotPlutusInterface/PreBalance.hs, test/Spec/MockContract.hs
Based on: #42
This PR introduces a way to delay the signing of transactions. This could be useful when we don't want to store the signing key(s) on the bot server. We still need their verification keys, in the same folder and in the same format as the signing keys, only with a `vkey` file extension.
=> Add the option to manually sign transactions

src/BotPlutusInterface/UtxoParser.hs, test/Spec/BotPlutusInterface/UtxoParser.hs
In a project where we use bot-plutus-interface, we use a non utf8 tokenname (it is a hash of a few things), so the current implementation would fail.
It turned out that we don't need to explicitly decode the tokenname from hex to a utf8 ByteString, it can be decoded straight into bs and it would still be interpreted the same way inside the Plutus code.
The cli adds a 0x prefix for raw bytestring tokennames, but we can simply skip over that.
=> Decoding raw ByteString TokenNames

README.md, bot-plutus-interface.cabal, src/BotPlutusInterface/Balance.hs, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/Contract.hs, test/Spec.hs, test/Spec/BotPlutusInterface/Balance.hs, test/Spec/BotPlutusInterface/Contract.hs, test/Spec/MockContract.hs
This interalises ada balancing, no longer relying on `cardano-cli transaction build`, and always building raw.
This means the Tx returned from `submitTx` or `balanceTx` is identical to the one submitted to the chain.
It also tweaks the balancing loop a bit to be more correct.
As such, `PreBalance` has been renamed to `Balance`
In order to handle the now changing txid of transaction as they are balanced, the tests were changed to now support a "?" in assertCommandHistory. Anywhere where a "?" is used in an expected command is seen as identical to up to the next space in the actual command.
See it as a regex `^[^ ]+(?= )`.
e.g.
```
this is an example actual command
```
As an actual command would compare equal to:
```
this is an example ? command
```
=> Fully internalise balancing, fix tests

.github/workflows/integrate.yaml, Makefile, bot-plutus-interface.cabal, cabal.project, examples/plutus-game/app/Main.hs, examples/plutus-nft/app/Main.hs, examples/plutus-transfer/app/Main.hs, src/BotPlutusInterface/Files.hs, src/BotPlutusInterface/Server.hs, test/Spec/BotPlutusInterface/Server.hs
=> Convert Text to TxId, update examples

README.md, examples/plutus-game/app/Main.hs, examples/plutus-nft/app/Main.hs, examples/plutus-transfer/app/Main.hs, src/BotPlutusInterface/Contract.hs, src/BotPlutusInterface/Types.hs
Just a small change
Solves: #61
=> Add tip polling interval configuration

src/BotPlutusInterface/Balance.hs, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/Contract.hs, src/BotPlutusInterface/Effects.hs, test/Spec/MockContract.hs
When operating with a remote CLI, I noticed a few issues:
- Balancing transactions required the signing keys file to be on the remote machine, but they weren't written until submission
- The `txs` folder is always created on the local machine, whereas, if we're running remote, it needs to be on the remote machine
- Various files and directories are created in non-optimum places
=> Fix signing keys and txs folder on remote

.github/workflows/integrate.yaml, Makefile, flake.nix
Following this, all examples build as part of CI (they did before, but now its more clear), and the nix shell has jq and websocat included.
=> Add jq and websocat, split up lib and examples build

test/Spec/MockContract.hs
This still fails the tests, because the txId is different then expected, but I think this should be easier to fix. Of course it's still a bit dirty idea, so if you have any better solutions this can be scrapped.
=> Almost fix tests with a hacky solution

src/BotPlutusInterface/Contract.hs
This PR fixes risk of getting `UnknownTxIns` that can happen during statistics collection, which is critical for current way `plutip` using `bpi`.
Problem:
* statistics collected by `bpi` include transaction execution budgets; to get those budgets estimation is performed, but it happens already after transaction is submitted, so depending on how fast transaction will be processed, there could be no required utxo's available anymore, which will lead to `UnknownTxIns` error
Changes:
* statistics calculation and saving moved to the point before transaction submission happens
=> Fix risk of getting `UnknownTxIns` during statistics saving

flake.lock, flake.nix
This updates `cardano-node` to [`73f9a746362695dc2cb63ba757fbcabb81733d23`](https://github.com/input-output-hk/cardano-node/tree/73f9a746362695dc2cb63ba757fbcabb81733d23) - and also the relevant dependencies.
It avoids touching the `plutus` and `plutus-apps` revisions because those are filled with trouble :)
I did set `flake = false` for `cardano-node` because otherwise, I was getting circular deps (bad nix code in `cardano-node`). Unsure if this is an undesirable change.
=> Update cardano-node to 1.34.1

bot-plutus-interface.cabal, flake.lock, src/BotPlutusInterface/Balance.hs, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/Contract.hs, test/Spec/BotPlutusInterface/Balance.hs, test/Spec/BotPlutusInterface/Contract.hs
Based on @sadMaxim 's work
In this PR we're removing min UTxO calculation done by the CLI, in favour of using `adjustUnbalancedTx`
=> Add missing effects

bot-plutus-interface.cabal, test/Spec/BotPlutusInterface/Contract.hs
CLI commands are pretty long, and can be hard to find the differences, so I added some pretty diff there.
Example result:
```
Send ada to address without change:                            FAIL (0.09s)
test/Spec/BotPlutusInterface/Contract.hs:907:
command at index 8 was incorrect:
Expected:
▼ ▼▼▼▼▼
cardano-cli transaction build-raw --babbage-era --tx-in e406b0cf676fc2b1a9edb061
7f259ad025c20ea6f0333820aa7cef1bfe7302e5#0 --tx-out addr1vyxk54m7j3q6mrkevcunryr
wf4p7e68c93cjk8gzxkhlkpsjpczl2+1000 --required-signer ./signing-keys/signing-key
-cb9358529df4729c3246a2a033cb9821abbfd16de4888005904abc41.skey --fee 200 --proto
▼
col-params-file ./protocol.json --out-file ./txs/tx-?.raw
Got:
cardano-cli transaction build-raw --alonzo-era --tx-in e406b0cf676fc2b1a9edb0617
▲▲▲▲▲ …
```
=> Pretty print test results

bot-plutus-interface.cabal, flake.lock, flake.nix, src/BotPlutusInterface/Balance.hs, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/Contract.hs, src/BotPlutusInterface/Files.hs, src/BotPlutusInterface/TimeSlot.hs, src/BotPlutusInterface/UtxoParser.hs, test/Spec.hs, test/Spec/BotPlutusInterface/AdjustUnbalanced.hs, test/Spec/BotPlutusInterface/Balance.hs, test/Spec/BotPlutusInterface/Collateral.hs, test/Spec/BotPlutusInterface/Config.hs, test/Spec/BotPlutusInterface/Contract.hs, test/Spec/BotPlutusInterface/ContractStats.hs, test/Spec/BotPlutusInterface/TxStatusChange.hs, test/Spec/BotPlutusInterface/UtxoParser.hs, test/Spec/MockContract.hs
Update `plutus-apps` to current (61ad6132e94a2f8edcf2d1862751e515c8d65e94) latest commit of `next-node`.
It is still custom branch for  `plutus-apps` only because of missing import of `getUnspentTxOutsAtAddress`. 
PR to put it back: https://github.com/input-output-hk/plutus-apps/pull/664
=> Vasil compliance: update to latest `plutus-apps` `next-node` (node 1.35.3)

src/BotPlutusInterface/Balance.hs, src/BotPlutusInterface/CardanoCLI.hs, src/BotPlutusInterface/Contract.hs
=> Add More `WalletAPIError` Types

src/BotPlutusInterface/Balance.hs, test/Spec/BotPlutusInterface/Balance.hs
This partitions input UTxOs into two groups: those with and without datums, and only balances those without datums. This is because some protocols require that UTxOs from validators not be changed when used as input to other validators.
Note that this fails the (only, to my knowledge) test where this would make a difference. However, this may just be because the test in question is too rigid, since it seems to check that the generated Transaction is exactly the same as it suspects.
=> Don't add change to UTxOs with Datums when Balancing Transactions

src/BotPlutusInterface/Balance.hs, src/BotPlutusInterface/CardanoNode/Effects.hs, src/BotPlutusInterface/ChainIndex.hs, src/BotPlutusInterface/Collateral.hs, src/BotPlutusInterface/Effects.hs, test/Spec.hs, test/Spec/BotPlutusInterface/Collateral.hs, test/Spec/BotPlutusInterface/Contract.hs, test/Spec/MockContract.hs
This PR:
* Adds handling of missing cases when collateral should not be returned by chain-index responses
* Adds node query effect like `UtxosAt ` but with filtering - `UtxosAtExcluding`
* Enables other collateral tests (they were not included to suite for some reason)
* Fixes some collateral-affected tests
=> Fix chain index query filtering

README.md, src/BotPlutusInterface/Collateral.hs, src/BotPlutusInterface/Files.hs, test/Spec/MockContract.hs
- Fixes collateral utxo being sent always to an enterprise address, ignoring `pcOwnStakePubKeyHash`.
- In `readPrivateKeys` matches both on extension and on file name, allowing for stake keys to be saved into `signing-keys` directory together with payment keys and not being mixed up.
Aboves don't change any existing behavior of bpi. 
TODO: Use staking keys for signing Tx, needs newest plutus-apps
=>  Support for addresses with staking keys [Plutip's #103].

README.md, src/BotPlutusInterface/Contract.hs
With this PR BPI will try to create collateral _before_ any user contract is executed.
If creation fails - contract execution will be aborted.
This behavior should fix the following possible scenario: 
1. user calls `utxosAt` in the contract (first contract executed with BPI in current session)
2. gets 1st UTxO from the result of `utxosAt` and uses it as transaction input
3. submits unbalanced or balances transaction
4. transaction fails because UTxO used as input could be consumed during collateral creation, which happens during balancing
=> Adjusting collateral creation
